#!/usr/bin/env bash

check_factor()
{
	num=$1
	last=${1: -1}
	x=1

	if [ $((last%2)) -eq 0  ]
	then
		x=2
	elif [ $((last%5)) -eq 0  ]
	then
		x=5
	else
		result=$(factor "$num")
		rr=($result)
		x=${rr[1]}
	fi 
	
	no=$(echo "$num / $x" | bc)
	echo "$num=$no*$x"
}


if [ $# -ne 1 ]
then
	echo 'Usage: factors <file>'
	exit 1
else
	while read i
	do
		check_factor $i
	done < "$1"
fi
