#!/usr/bin/env bash

check_factor()
{
	num=$1
        result=$(factor "$num")
        rr=($result)
        x=${rr[1]}

        no=$(echo "$num / $x" | bc)
        echo "$num=$no*$x"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                check_factor $i

        done < "$1"
fi

